package com.myteam.lists;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Lists implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<java.lang.String> listOfStrings;
	private java.util.List<java.lang.Integer> listOfIntegers;
	public Lists() {
	}

	public java.util.List<java.lang.String> getListOfStrings() {
		return this.listOfStrings;
	}

	public void setListOfStrings(java.util.List<java.lang.String> listOfStrings) {
		this.listOfStrings = listOfStrings;
	}

	public java.util.List<java.lang.Integer> getListOfIntegers() {
		return this.listOfIntegers;
	}

	public void setListOfIntegers(
			java.util.List<java.lang.Integer> listOfIntegers) {
		this.listOfIntegers = listOfIntegers;
	}

	public Lists(java.util.List<java.lang.String> listOfStrings,
			java.util.List<java.lang.Integer> listOfIntegers) {
		this.listOfStrings = listOfStrings;
		this.listOfIntegers = listOfIntegers;
	}

}